# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yongchao's Quantum Zone
email: tyc2015@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the frontier of quantum computing
baseurl: "/canvas" # the subpath of your site, e.g. /blog
url: "http://yct.im/canvas" # the base hostname & protocol for your sit
github_username:  adaptivefinances

# Build settings
markdown: kramdown
